GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmFmNWU3MDgwMTIxZjc3Y2NjNzA5NjQiLCJpYXQiOjE2NTU2NjA0MDIsImV4cCI6MTY1NTc0NjgwMn0.OelI4I6J__6As-8UF8LwT423UPALN_Bg5NhQJVkcZkc